[package]
name = "rjaws"
version = "3.1.0-PRE"
edition = "2021"

[[bin]]
name = "jaws"
path ="src/main.rs"

[dependencies]
# General Dependencies
tokio = { version = "1", features = ["full"] }   # Required for AWS
clap = { version = "4.3.19", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
futures = "0.3"
async-trait = "0.1"
colored = "2"
tabled = "0.14"
termion = "2"
subprocess = "0.2"
signal-hook = "0.3.15"

# AWS Dependencies
aws-config = "0.56.0"
aws-sdk-sts = "0.29.0"
aws-sdk-ec2 = "0.29.0"
aws-sdk-iam = "0.29.0"
aws-sdk-ssm = "0.29.0"
