[package]
name = "rjaws"
version = "0.1.0"
edition = "2021"

[dependencies]
# General Dependencies
tokio = { version = "1", features = ["full"] }   # Required for AWS
clap = { version = "4.1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
futures = "0.3"
async-trait = "0.1"
colored = "2"
tabled = "0.10"

# AWS Dependencies
aws-config = "0.54"
aws-sdk-sts = "0.24"
aws-sdk-ec2 = "0.24"
